/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.time;
import dao.custom.QueryDAO;
import dao.custom.impl.QueryDAOImpl;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;

/**
 *
 * @author User
 */
public class Admindash extends javax.swing.JFrame {

     QueryDAO queryDAO=new QueryDAOImpl();
    /**
     * Creates new form Admindash
     */
    public Admindash() {
        initComponents();
       pnl4.setBackground(new java.awt.Color(0,0,0,170));
       pnl5.setBackground(new java.awt.Color(0,0,0,170));
       pnl6.setBackground(new java.awt.Color(0,0,0,170));
       pnl7.setBackground(new java.awt.Color(0,0,0,170));
       
        autoSettime();
        settDate();
       getCount();
       getCounttwo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnadmindoct = new javax.swing.JButton();
        btnadminshedule = new javax.swing.JButton();
        btnadminapecialtype = new javax.swing.JButton();
        btmadminusers = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        pnl4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        pnl5 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        pnl6 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        pnl7 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        lblcount = new javax.swing.JLabel();
        lblcounttwo = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();
        lbltime = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnadmindoct.setBackground(new java.awt.Color(204, 204, 204));
        btnadmindoct.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        btnadmindoct.setText("Doctors");
        btnadmindoct.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnadmindoct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnadmindoctMouseClicked(evt);
            }
        });
        btnadmindoct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadmindoctActionPerformed(evt);
            }
        });
        jPanel1.add(btnadmindoct, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 170, 50));

        btnadminshedule.setBackground(new java.awt.Color(204, 204, 204));
        btnadminshedule.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        btnadminshedule.setText("Schedule");
        btnadminshedule.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnadminshedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadminsheduleActionPerformed(evt);
            }
        });
        jPanel1.add(btnadminshedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 170, 50));

        btnadminapecialtype.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        btnadminapecialtype.setText("Special Types");
        btnadminapecialtype.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnadminapecialtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadminapecialtypeActionPerformed(evt);
            }
        });
        jPanel1.add(btnadminapecialtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 170, 50));

        btmadminusers.setBackground(new java.awt.Color(204, 204, 204));
        btmadminusers.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        btmadminusers.setText("Users");
        btmadminusers.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btmadminusers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmadminusersActionPerformed(evt);
            }
        });
        jPanel1.add(btmadminusers, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, 170, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 305)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setText("+");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -40, 250, 260));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 710));

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/Logout Rounded Left_24px.png"))); // NOI18N
        jButton1.setText("Log Out");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 30, 110, 40));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("DURDANS HOSPITAL");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 850, 80));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 1150, 80));

        pnl4.setBackground(new java.awt.Color(0, 0, 0));
        pnl4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/Doctor Male_96px.png"))); // NOI18N
        jButton2.setText("MANAGE DOCTOR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        pnl4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 300, 120));

        getContentPane().add(pnl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 360, 240));

        pnl5.setBackground(new java.awt.Color(0, 0, 0));
        pnl5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/Timesheet_96px.png"))); // NOI18N
        jButton3.setText("MANAGE SHEDULE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        pnl5.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 70, -1, 110));

        getContentPane().add(pnl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 120, 340, 240));

        pnl6.setBackground(new java.awt.Color(0, 0, 0));
        pnl6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/Doctor Female_96px.png"))); // NOI18N
        jButton4.setText("SPECIAL TYPE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        pnl6.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 290, -1));

        getContentPane().add(pnl6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 360, 250));

        pnl7.setBackground(new java.awt.Color(0, 0, 0));
        pnl7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/Join_96px.png"))); // NOI18N
        jButton5.setText("MANAGE USERS");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        pnl7.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 280, 100));

        getContentPane().add(pnl7, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, 340, 250));

        lblcount.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        lblcount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcount.setText("00");
        getContentPane().add(lblcount, new org.netbeans.lib.awtextra.AbsoluteConstraints(1147, 260, 110, 70));

        lblcounttwo.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        lblcounttwo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcounttwo.setText("00");
        getContentPane().add(lblcounttwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 430, 80, 80));

        lbldate.setBackground(new java.awt.Color(0, 0, 0));
        lbldate.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbldate.setForeground(new java.awt.Color(0, 102, 204));
        lbldate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/Calendar_30px.png"))); // NOI18N
        lbldate.setText("Date");
        getContentPane().add(lbldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 596, 260, -1));

        lbltime.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbltime.setForeground(new java.awt.Color(0, 102, 204));
        lbltime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/Time_30px.png"))); // NOI18N
        lbltime.setText("time");
        getContentPane().add(lbltime, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 660, 250, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Doctors");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 200, 150, 60));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("Status Update");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 90, 260, 50));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Appoinments");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 350, 210, 90));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 150, 260, 10));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/123.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 1150, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       new Loginframe().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnadmindoctMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnadmindoctMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_btnadmindoctMouseClicked

    private void btnadmindoctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadmindoctActionPerformed
        new MangeDoctors().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnadmindoctActionPerformed

    private void btnadminsheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadminsheduleActionPerformed
        new Shedule().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnadminsheduleActionPerformed

    private void btnadminapecialtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadminapecialtypeActionPerformed
        new SpecialType().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnadminapecialtypeActionPerformed

    private void btmadminusersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmadminusersActionPerformed
        new User().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btmadminusersActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new MangeDoctors().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new Shedule().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new SpecialType().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new User().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admindash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admindash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admindash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admindash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admindash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmadminusers;
    private javax.swing.JButton btnadminapecialtype;
    private javax.swing.JButton btnadmindoct;
    private javax.swing.JButton btnadminshedule;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblcount;
    private javax.swing.JLabel lblcounttwo;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lbltime;
    private javax.swing.JPanel pnl4;
    private javax.swing.JPanel pnl5;
    private javax.swing.JPanel pnl6;
    private javax.swing.JPanel pnl7;
    // End of variables declaration//GEN-END:variables

    private void autoSettime() {
       new Thread (new Runnable() {
            @Override
            public void run() {
                while(true){   
                    Date curDate = new Date();
                    SimpleDateFormat dateFormat =new SimpleDateFormat("HH:mm:ss:aa");
                    String currentTime =dateFormat.format(curDate);
                    lbltime.setText(currentTime);
                    try{
                        Thread.sleep(1000);
                    }catch(InterruptedException ex){
                        
                    }
                    
                }
            }
        }).start();
    }

    private void settDate() {
       lbldate.setText(LocalDate.now().toString()); 
    }

 private void getCount() {
       int row=queryDAO.rowCount();
       lblcount.setText(row+"");
    }

    private void getCounttwo() {
       int row=queryDAO.rowCounttwo();
       lblcounttwo.setText(row+"");
    }

   
}
