/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.AppoinmentController;
import static controller.AppoinmentController.deleteAppoinment;
import controller.DoctorController;
import controller.SheduleController;
import dao.DAOFactory;
import dao.SuperDAO;
import dao.custom.SheduleDAO;
import dto.AppoinmentDTO;
import dto.DoctorDTO;
import dto.SheduleDTO;
import entity.Shedule;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author User
 */
public class Apponmnet extends javax.swing.JFrame {

  private DefaultTableModel dtm;
    
    /**
     * Creates new form Apponmnet
     */
    public Apponmnet() {
        initComponents();
        setAppoinmentNumber();
        loadAllDoctorsID();
        autoSettime();
        settDate();
        dtm=(DefaultTableModel)tblappoinment.getModel();
        getAllAppoinmnet();
//         pnlappadate.setBackground(new java.awt.Color(0,0,0,125));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtAppoinmentNumber = new javax.swing.JTextField();
        txtPatientId = new javax.swing.JTextField();
        txtDoctorName = new javax.swing.JTextField();
        txtpatientTel = new javax.swing.JTextField();
        cmbDoctShedule = new javax.swing.JComboBox<>();
        cmbSelectDoctor = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtdoctDescription = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtpateintName = new javax.swing.JTextField();
        txtAppoinmentDate = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblappoinment = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        lbltime = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();
        btnDone = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pnlappadate = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(0, 153, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(194, 216, 249));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 0, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SPECIAL TYPE");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 20, 110, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/appionmt.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 90, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel1.setText("MANAGE APPOINMENT");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 580, 60));

        jButton2.setBackground(new java.awt.Color(0, 0, 153));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/Home2_48px.png"))); // NOI18N
        jButton2.setText("HOME");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 20, 110, 50));

        jButton3.setBackground(new java.awt.Color(0, 0, 153));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("SHEDULE");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 20, 110, 50));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 80));

        jPanel4.setBackground(new java.awt.Color(232, 228, 228));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/two.png"))); // NOI18N
        jLabel5.setText("Appoinment Number");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/two.png"))); // NOI18N
        jLabel16.setText("Patient NIC");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/two.png"))); // NOI18N
        jLabel17.setText("Patient Name");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/two.png"))); // NOI18N
        jLabel18.setText("Patient Tel ");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/two.png"))); // NOI18N
        jLabel19.setText("Select Doctor");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/two.png"))); // NOI18N
        jLabel20.setText("Sesion");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/two.png"))); // NOI18N
        jLabel21.setText("Date");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        txtAppoinmentNumber.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtAppoinmentNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAppoinmentNumber.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtAppoinmentNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAppoinmentNumberActionPerformed(evt);
            }
        });
        jPanel4.add(txtAppoinmentNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 250, 30));

        txtPatientId.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtPatientId.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(txtPatientId, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 250, 30));

        txtDoctorName.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtDoctorName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtDoctorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoctorNameActionPerformed(evt);
            }
        });
        jPanel4.add(txtDoctorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 250, 30));

        txtpatientTel.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtpatientTel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtpatientTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpatientTelActionPerformed(evt);
            }
        });
        jPanel4.add(txtpatientTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 250, 30));

        cmbDoctShedule.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cmbDoctShedule.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmbDoctShedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbDoctSheduleMouseClicked(evt);
            }
        });
        jPanel4.add(cmbDoctShedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 160, 250, 30));

        cmbSelectDoctor.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cmbSelectDoctor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmbSelectDoctor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbSelectDoctorItemStateChanged(evt);
            }
        });
        jPanel4.add(cmbSelectDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 60, 250, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/two.png"))); // NOI18N
        jLabel9.setText("Description");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 170, 40));

        txtdoctDescription.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtdoctDescription.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(txtdoctDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 110, 250, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/two.png"))); // NOI18N
        jLabel10.setText("Doctor Name");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        txtpateintName.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtpateintName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtpateintName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpateintNameActionPerformed(evt);
            }
        });
        jPanel4.add(txtpateintName, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 250, 30));

        txtAppoinmentDate.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtAppoinmentDate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(txtAppoinmentDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 250, 30));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 1030, 250));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblappoinment.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblappoinment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Appoinment Number", "Patient Name", "Patient NIC", "Doctor Name", "Description", "Date", "Sesion", "Patient Tel"
            }
        ));
        tblappoinment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblappoinmentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblappoinment);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 1010, 240));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Appoinment Details");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 320, 40));

        lbltime.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbltime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/Time_30px.png"))); // NOI18N
        lbltime.setText("time");
        jPanel3.add(lbltime, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 260, -1));

        lbldate.setBackground(new java.awt.Color(0, 0, 0));
        lbldate.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbldate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/Calendar_30px.png"))); // NOI18N
        lbldate.setText("Date");
        jPanel3.add(lbldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 290, 40));

        btnDone.setBackground(new java.awt.Color(255, 0, 51));
        btnDone.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnDone.setText("PAYMENT");
        btnDone.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneActionPerformed(evt);
            }
        });
        jPanel3.add(btnDone, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 310, 170, 40));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 1030, 350));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUpdate.setBackground(new java.awt.Color(255, 255, 204));
        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnUpdate.setText("UPDATE APPOINMENT");
        btnUpdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel5.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 210, 50));

        btnDelete.setBackground(new java.awt.Color(255, 0, 51));
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnDelete.setText("DELETE APPOINMENT");
        btnDelete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel5.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 210, 50));

        btnRefresh.setBackground(new java.awt.Color(0, 153, 51));
        btnRefresh.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnRefresh.setText("REFRESH APPOINMENT");
        btnRefresh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        jPanel5.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 210, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/Update_60px.png"))); // NOI18N
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 60));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/Delete_60px.png"))); // NOI18N
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 60, 50));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/Refresh_60px.png"))); // NOI18N
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 60, 50));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 90, 300, 300));

        pnlappadate.setBackground(new java.awt.Color(255, 255, 255));
        pnlappadate.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/bright-cardiac-cardiology-433267.jpg"))); // NOI18N
        pnlappadate.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 300));

        jPanel2.add(pnlappadate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 400, 300, 300));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new SpecialType().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtDoctorNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoctorNameActionPerformed

    }//GEN-LAST:event_txtDoctorNameActionPerformed

    private void txtpateintNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpateintNameActionPerformed
        txtPatientId.requestFocus();
    }//GEN-LAST:event_txtpateintNameActionPerformed

    private void cmbSelectDoctorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbSelectDoctorItemStateChanged

        try {
            String DoctID=cmbSelectDoctor.getSelectedItem().toString();
            DoctorDTO searchDoctor=DoctorController.searchDoctor(DoctID);
            txtDoctorName.setText(searchDoctor.getDoctName());
            txtdoctDescription.setText(searchDoctor.getDoctSpecialType());
            
            ArrayList<DoctorDTO> allDoctors=DoctorController.getAllDoctor();
            String date=null;
//            String name=null;
            String value=null;
            cmbDoctShedule.removeAllItems();
            for(DoctorDTO d:allDoctors){
                if (d.getDoctId().equals(DoctID)) {
                    SheduleDAO dao = (SheduleDAO) DAOFactory.getInstance().getDAO(DAOFactory.DAOTypes.SHEDULE);   
                    Shedule search = dao.search(DoctID);
                    date=search.getShedMon();
                    value = "Monday"+ " "+ date;
                    cmbDoctShedule.addItem(value);
                    date=search.getShedTue();
                    value = "Tuesday"+ " "+ date;
                    cmbDoctShedule.addItem(value);
                    date=search.getShedWed();
                    value = "Wednesday"+ " "+ date;
                    cmbDoctShedule.addItem(value);
                     date=search.getShedThu();
                    value = "Thursday"+ " "+ date;
                    cmbDoctShedule.addItem(value);
                    date=search.getShedFri();
                    value = "Friday"+ " "+ date;
                    cmbDoctShedule.addItem(value);
                     date=search.getShedSat();
                    value = "Saturday"+ " "+ date;
                    cmbDoctShedule.addItem(value);
                     date=search.getShedSun();
                    value = "Sunday"+ " "+ date;
                    cmbDoctShedule.addItem(value);
                }else{
                    
//                JOptionPane.showMessageDialog("Error", JOptionPane.ERROR_MESSAGE);
                }
//                cmbSelectDoctor.addItem(d.getDoctId());
            }
            
              
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cmbSelectDoctorItemStateChanged

        
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       
    }//GEN-LAST:event_formWindowOpened

    private void cmbDoctSheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbDoctSheduleMouseClicked
       
        
    }//GEN-LAST:event_cmbDoctSheduleMouseClicked

    private void btnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneActionPerformed
        
        try {
            String appoinID=txtAppoinmentNumber.getText();
            String patientName=txtpateintName.getText();
            String patientNIC=txtPatientId.getText();
            String doctName=txtDoctorName.getText();
            String description=txtdoctDescription.getText();
            String date=txtAppoinmentDate.getText();
            String sesion=cmbDoctShedule.getSelectedItem().toString();
            int tel=Integer.parseInt(txtpatientTel.getText());
            
            AppoinmentDTO appoinModel = new AppoinmentDTO(appoinID,patientName, patientNIC, doctName, description, date, sesion, tel);
            boolean addAppoinment=AppoinmentController.addAppoinment(appoinModel);
            if(addAppoinment){
                JOptionPane.showMessageDialog(this, "Make Appoinmnet");
                clearAll();
                getAllAppoinmnet();
            }else{
                JOptionPane.showMessageDialog(this, "Failed");
            }
            
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
        new Payment().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDoneActionPerformed

    private void tblappoinmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblappoinmentMouseClicked
            int selectedRow=tblappoinment.getSelectedRow();
            String appoinid=dtm.getValueAt(selectedRow, 0).toString();
            String patientName=dtm.getValueAt(selectedRow,1).toString();
            String patientNIC=dtm.getValueAt(selectedRow, 2).toString();
            String doctName=dtm.getValueAt(selectedRow, 3).toString();
            String description=dtm.getValueAt(selectedRow, 4).toString();
            String date=dtm.getValueAt(selectedRow, 5).toString();
            String sesion=dtm.getValueAt(selectedRow, 6).toString();
            String tel=dtm.getValueAt(selectedRow, 7).toString();
            txtAppoinmentNumber.setText(appoinid);
            txtpateintName.setText(patientName);
            txtPatientId.setText(patientNIC);
            txtDoctorName.setText(doctName);
            txtdoctDescription.setText(description);
            txtAppoinmentDate.setText(date);
            cmbDoctShedule.setSelectedItem(sesion);
            txtpatientTel.setText(tel);
    }//GEN-LAST:event_tblappoinmentMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
      try {
          String appoinID=txtAppoinmentNumber.getText();
          String patientName=txtpateintName.getText();
          String patientNIC=txtPatientId.getText();
          String doctName=txtDoctorName.getText();
          String description=txtdoctDescription.getText();
          String date=txtAppoinmentDate.getText();
          String sesion=cmbDoctShedule.getSelectedItem().toString();
          int tel=Integer.parseInt(txtpatientTel.getText());
          AppoinmentDTO appoinModel=new AppoinmentDTO(appoinID, patientName, patientNIC, doctName, description, date, sesion, tel);
          boolean updateAppoinment=AppoinmentController.updateAppoinment(appoinModel);
          if(updateAppoinment){
              getAllAppoinmnet();
              clearAll();
              JOptionPane.showMessageDialog(this, "Update Appoinment");
          }else{
              JOptionPane.showMessageDialog(this, "Failed");
          }
          
      } catch (ClassNotFoundException ex) {
          Logger.getLogger(Apponmnet.class.getName()).log(Level.SEVERE, null, ex);
      } catch (SQLException ex) {
          Logger.getLogger(Apponmnet.class.getName()).log(Level.SEVERE, null, ex);
      }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
      try {
          String appoinmentID=txtAppoinmentNumber.getText();
          boolean deleteAppoinment=deleteAppoinment(appoinmentID);
          if(deleteAppoinment){
             JOptionPane.showMessageDialog(this, "Delete Appoinment");
             clearAll();
             getAllAppoinmnet();
          }else{
              JOptionPane.showMessageDialog(this, "Failed");
          }
      } catch (ClassNotFoundException ex) {
          JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
      } catch (SQLException ex) {
          JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
      }
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        clearAll();
        getAllAppoinmnet();
       
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void txtpatientTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpatientTelActionPerformed
           
    }//GEN-LAST:event_txtpatientTelActionPerformed

    private void txtAppoinmentNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAppoinmentNumberActionPerformed
        String appoinmentID=txtAppoinmentNumber.getText();
      try {
          AppoinmentDTO searchAppoinmnet=AppoinmentController.searchAppoinment(appoinmentID);
          clearAll();
          txtAppoinmentNumber.setText(searchAppoinmnet.getAppoinmentNum());
          txtpateintName.setText(searchAppoinmnet.getPatientName());
          txtPatientId.setText(searchAppoinmnet.getPatientId());
          txtDoctorName.setText(searchAppoinmnet.getDoctorName());
          txtdoctDescription.setText(searchAppoinmnet.getDescription());
          txtAppoinmentDate.setText(searchAppoinmnet.getAppoinmentdate());
          cmbDoctShedule.setSelectedItem(searchAppoinmnet.getShedule());
          txtpatientTel.setText(searchAppoinmnet.getPatientTel()+"");
      } catch (ClassNotFoundException ex) {
          JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
      } catch (SQLException ex) {
          JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
      }
        
    }//GEN-LAST:event_txtAppoinmentNumberActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new ReceptionDash().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new view.Shedule().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Apponmnet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Apponmnet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Apponmnet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Apponmnet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Apponmnet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDone;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbDoctShedule;
    private javax.swing.JComboBox<String> cmbSelectDoctor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lbltime;
    private javax.swing.JPanel pnlappadate;
    private javax.swing.JTable tblappoinment;
    private javax.swing.JTextField txtAppoinmentDate;
    private javax.swing.JTextField txtAppoinmentNumber;
    private javax.swing.JTextField txtDoctorName;
    private javax.swing.JTextField txtPatientId;
    private javax.swing.JTextField txtdoctDescription;
    private javax.swing.JTextField txtpateintName;
    private javax.swing.JTextField txtpatientTel;
    // End of variables declaration//GEN-END:variables

    private void setAppoinmentNumber() {
        int number=new Random().nextInt(99999999);
        String prefix="A";
        txtAppoinmentNumber.setText(prefix+number);
    }

    private void loadAllDoctorsID() {
        try {
            cmbSelectDoctor.removeAll();
            ArrayList<DoctorDTO> allDoctors=DoctorController.getAllDoctor();
            for(DoctorDTO d:allDoctors){
                cmbSelectDoctor.addItem(d.getDoctId());
            }
            
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
    }

    private void autoSettime() {
       new Thread (new Runnable() {
            @Override
            public void run() {
                while(true){   
                    Date curDate = new Date();
                    SimpleDateFormat dateFormat =new SimpleDateFormat("HH:mm:ss:aa");
                    String currentTime =dateFormat.format(curDate);
                    lbltime.setText(currentTime);
                    try{
                        Thread.sleep(1000);
                    }catch(InterruptedException ex){
                        
                    }
                    
                }
            }
        }).start();
    }

    private void settDate() {
       lbldate.setText(LocalDate.now().toString()); 
    }

    private void clearAll() {
        txtAppoinmentNumber.setText("");
        txtpateintName.setText("");
        txtPatientId.setText("");
        txtDoctorName.setText("");
        txtdoctDescription.setText("");
        txtAppoinmentDate.setText("");
        txtpatientTel.setText("");
    }

    private void getAllAppoinmnet() {
      try {
          dtm.setRowCount(0);
          ArrayList<AppoinmentDTO> allAppoinment=AppoinmentController.getAllAppoinment();
          for(AppoinmentDTO app:allAppoinment){
              Object[] rowData={app.getAppoinmentNum(),app.getPatientName(),app.getPatientId(),app.getDoctorName(),app.getDescription(),app.getAppoinmentdate(),app.getShedule(),app.getPatientTel()};
              dtm.addRow(rowData);
          }
          
      } catch (ClassNotFoundException ex) {
          Logger.getLogger(Apponmnet.class.getName()).log(Level.SEVERE, null, ex);
      } catch (SQLException ex) {
          Logger.getLogger(Apponmnet.class.getName()).log(Level.SEVERE, null, ex);
      }
    }

    
    
   
}
