/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.DoctorController;
import dao.custom.QueryDAO;
import dao.custom.impl.QueryDAOImpl;
import dto.DoctorDTO;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author User
 */
public class MangeDoctors extends javax.swing.JFrame {

    private DefaultTableModel dtm;
    
   
    /**
     * Creates new form MangeDoctors
     */
    public MangeDoctors() {
        initComponents();
        dtm = (DefaultTableModel)tblDoctorDetails.getModel();
        getAllDoctors();
        autoSettime();
        settDate();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnusers = new javax.swing.JButton();
        btnshedule = new javax.swing.JButton();
        btnspecialtype = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtDoctorId = new javax.swing.JTextField();
        txtDoctorName = new javax.swing.JTextField();
        txtDoctorAddress = new javax.swing.JTextField();
        txtDoctorHospital = new javax.swing.JTextField();
        txtDoctorSpecialtype = new javax.swing.JTextField();
        txtDoctorIdCard = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDoctorTel = new javax.swing.JTextField();
        txtDoctorGender = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDoctorDetails = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();
        lbltime = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnDoctorSave = new javax.swing.JButton();
        btnDoctorUpdate = new javax.swing.JButton();
        btnDoctorDelete = new javax.swing.JButton();
        btnDoctorRefersh = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(194, 216, 249));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 0, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/Home2_48px.png"))); // NOI18N
        jButton1.setText("HOME");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 20, 110, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/Stethoscope_60px.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 80));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel1.setText("MANAGE DOCTORS");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 480, 60));

        btnusers.setBackground(new java.awt.Color(0, 0, 153));
        btnusers.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnusers.setForeground(new java.awt.Color(255, 255, 255));
        btnusers.setText("USERS");
        btnusers.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnusers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnusersActionPerformed(evt);
            }
        });
        jPanel2.add(btnusers, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 20, 110, 50));

        btnshedule.setBackground(new java.awt.Color(0, 0, 153));
        btnshedule.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnshedule.setForeground(new java.awt.Color(255, 255, 255));
        btnshedule.setText("SHEDULE");
        btnshedule.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnshedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsheduleActionPerformed(evt);
            }
        });
        jPanel2.add(btnshedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, 110, 50));

        btnspecialtype.setBackground(new java.awt.Color(0, 0, 153));
        btnspecialtype.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnspecialtype.setForeground(new java.awt.Color(255, 255, 255));
        btnspecialtype.setText("SPECIAL TYPE");
        btnspecialtype.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnspecialtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnspecialtypeActionPerformed(evt);
            }
        });
        jPanel2.add(btnspecialtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 20, 110, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 80));

        jPanel4.setBackground(new java.awt.Color(232, 228, 228));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/two.png"))); // NOI18N
        jLabel5.setText("Doctor ID");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/two.png"))); // NOI18N
        jLabel16.setText("Doctor Name");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/two.png"))); // NOI18N
        jLabel17.setText("Address");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/two.png"))); // NOI18N
        jLabel18.setText("Hospital");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/two.png"))); // NOI18N
        jLabel20.setText("ID Card No");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/two.png"))); // NOI18N
        jLabel21.setText("Special Type");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, -1, -1));

        txtDoctorId.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtDoctorId.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtDoctorId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoctorIdActionPerformed(evt);
            }
        });
        jPanel4.add(txtDoctorId, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 230, 30));

        txtDoctorName.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtDoctorName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtDoctorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoctorNameActionPerformed(evt);
            }
        });
        jPanel4.add(txtDoctorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 240, 30));

        txtDoctorAddress.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtDoctorAddress.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtDoctorAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoctorAddressActionPerformed(evt);
            }
        });
        jPanel4.add(txtDoctorAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 230, 30));

        txtDoctorHospital.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtDoctorHospital.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtDoctorHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoctorHospitalActionPerformed(evt);
            }
        });
        jPanel4.add(txtDoctorHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 230, 30));

        txtDoctorSpecialtype.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtDoctorSpecialtype.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtDoctorSpecialtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoctorSpecialtypeActionPerformed(evt);
            }
        });
        jPanel4.add(txtDoctorSpecialtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 130, 240, 30));

        txtDoctorIdCard.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtDoctorIdCard.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtDoctorIdCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoctorIdCardActionPerformed(evt);
            }
        });
        jPanel4.add(txtDoctorIdCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 70, 240, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/two.png"))); // NOI18N
        jLabel2.setText("Gender");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 130, 40));

        txtDoctorTel.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtDoctorTel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtDoctorTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoctorTelActionPerformed(evt);
            }
        });
        jPanel4.add(txtDoctorTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 230, 30));

        txtDoctorGender.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtDoctorGender.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtDoctorGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoctorGenderActionPerformed(evt);
            }
        });
        jPanel4.add(txtDoctorGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 200, 240, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/two.png"))); // NOI18N
        jLabel6.setText("Tel Number");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 1020, 260));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDoctorDetails.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblDoctorDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Doctor ID", "Doctor Name", "Address", "ID Card No", "Hospital", "Special Type", "Tel Number", "Gender"
            }
        ));
        tblDoctorDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDoctorDetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDoctorDetails);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1020, 250));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Doctors Details");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 270, 40));

        lbldate.setBackground(new java.awt.Color(0, 0, 0));
        lbldate.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbldate.setForeground(new java.awt.Color(0, 51, 204));
        lbldate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/Calendar_30px.png"))); // NOI18N
        lbldate.setText("Date");
        jPanel3.add(lbldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 290, 40));

        lbltime.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbltime.setForeground(new java.awt.Color(0, 51, 204));
        lbltime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/Time_30px.png"))); // NOI18N
        lbltime.setText("time");
        jPanel3.add(lbltime, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 260, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 1030, 350));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDoctorSave.setBackground(new java.awt.Color(0, 102, 255));
        btnDoctorSave.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnDoctorSave.setText("SAVE DOCTOR");
        btnDoctorSave.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDoctorSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorSaveActionPerformed(evt);
            }
        });
        jPanel5.add(btnDoctorSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 190, 50));

        btnDoctorUpdate.setBackground(new java.awt.Color(255, 255, 204));
        btnDoctorUpdate.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnDoctorUpdate.setText("UPDATE DOCTOR");
        btnDoctorUpdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDoctorUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorUpdateActionPerformed(evt);
            }
        });
        jPanel5.add(btnDoctorUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 190, 50));

        btnDoctorDelete.setBackground(new java.awt.Color(255, 0, 51));
        btnDoctorDelete.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnDoctorDelete.setText("DELETE DOCTOR");
        btnDoctorDelete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDoctorDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorDeleteActionPerformed(evt);
            }
        });
        jPanel5.add(btnDoctorDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 190, 50));

        btnDoctorRefersh.setBackground(new java.awt.Color(0, 153, 51));
        btnDoctorRefersh.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnDoctorRefersh.setText("REFRESH DOCTOR");
        btnDoctorRefersh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDoctorRefersh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorRefershActionPerformed(evt);
            }
        });
        jPanel5.add(btnDoctorRefersh, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 190, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/Ok_60px.png"))); // NOI18N
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 60, 60));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/Update_60px.png"))); // NOI18N
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 70, 60));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/Delete_60px.png"))); // NOI18N
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 60, 50));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/Refresh_60px.png"))); // NOI18N
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 60, 50));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 90, 310, 280));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/bright-cardiac-cardiology-433267.jpg"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 384, 310, 300));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        new ReceptionDash().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtDoctorNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoctorNameActionPerformed
        txtDoctorAddress.requestFocus();
    }//GEN-LAST:event_txtDoctorNameActionPerformed

    private void txtDoctorAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoctorAddressActionPerformed
        txtDoctorIdCard.requestFocus();
    }//GEN-LAST:event_txtDoctorAddressActionPerformed

    private void txtDoctorIdCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoctorIdCardActionPerformed
        txtDoctorHospital.requestFocus();
    }//GEN-LAST:event_txtDoctorIdCardActionPerformed

    private void txtDoctorHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoctorHospitalActionPerformed
        txtDoctorSpecialtype.requestFocus();
    }//GEN-LAST:event_txtDoctorHospitalActionPerformed

    private void txtDoctorSpecialtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoctorSpecialtypeActionPerformed
        txtDoctorTel.requestFocus();
    }//GEN-LAST:event_txtDoctorSpecialtypeActionPerformed

    private void txtDoctorTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoctorTelActionPerformed
        txtDoctorGender.requestFocus();
    }//GEN-LAST:event_txtDoctorTelActionPerformed

    private void txtDoctorGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoctorGenderActionPerformed
        btnDoctorSave.requestFocus();
        btnDoctorSave.doClick();
    }//GEN-LAST:event_txtDoctorGenderActionPerformed

    private void btnDoctorSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorSaveActionPerformed

      try {
        String DoctId=txtDoctorId.getText();
        String DoctName=txtDoctorName.getText();
        String DoctAddress=txtDoctorAddress.getText();
        String DoctIdCardNum=txtDoctorIdCard.getText();
        String DoctHospital=txtDoctorHospital.getText();
        String DoctSpecialType=txtDoctorSpecialtype.getText();
        int DoctTel=Integer.parseInt(txtDoctorTel.getText());
        String DoctGende=txtDoctorGender.getText();
        
        DoctorDTO doctModel=new DoctorDTO(DoctId, DoctName, DoctAddress, DoctIdCardNum, DoctHospital, DoctSpecialType, DoctTel, DoctGende);
        boolean addDoctor = DoctorController.addDoctor(doctModel);
          if (addDoctor) {
              JOptionPane.showMessageDialog(this, "Add Doctor");
              clearAll();
              getAllDoctors();
          }else{
              JOptionPane.showMessageDialog(this, "Failed");
          }
        
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
              
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDoctorSaveActionPerformed

    private void tblDoctorDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDoctorDetailsMouseClicked
        int selectedRow = tblDoctorDetails.getSelectedRow(); 
        String id=dtm.getValueAt(selectedRow, 0).toString();
        String name=dtm.getValueAt(selectedRow, 1).toString();
        String address=dtm.getValueAt(selectedRow, 2).toString();
        String idcardnum=dtm.getValueAt(selectedRow, 3).toString();
        String hospital=dtm.getValueAt(selectedRow, 4).toString();
        String Specialtype=dtm.getValueAt(selectedRow, 5).toString();
        String tel=dtm.getValueAt(selectedRow, 6).toString();
        String gender=dtm.getValueAt(selectedRow, 7).toString();
        txtDoctorId.setText(id);
        txtDoctorName.setText(name);
        txtDoctorAddress.setText(address);
        txtDoctorIdCard.setText(idcardnum);
        txtDoctorHospital.setText(hospital);
        txtDoctorSpecialtype.setText(Specialtype); 
        txtDoctorTel.setText(tel);
        txtDoctorGender.setText(gender);
    }//GEN-LAST:event_tblDoctorDetailsMouseClicked

    private void btnDoctorDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorDeleteActionPerformed
      
        try {
            String DoctId=txtDoctorId.getText();
            boolean deleteDoctor = deleteDoctor(DoctId);
            
            if(deleteDoctor){
                JOptionPane.showMessageDialog(this, "Delete Doctor");
                clearAll();
                getAllDoctors();
            }else{
                JOptionPane.showMessageDialog(this, "Failed");
            }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
     
       
       
    }//GEN-LAST:event_btnDoctorDeleteActionPerformed

    private void btnDoctorUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorUpdateActionPerformed
        try {
            String DoctId=txtDoctorId.getText();
            String DoctName=txtDoctorName.getText();
            String DoctAddress=txtDoctorAddress.getText();
            String DoctIdCardNum=txtDoctorIdCard.getText();
            String DoctHospital=txtDoctorHospital.getText();
            String DoctSpecialType =txtDoctorSpecialtype.getText();
            int DoctTel =Integer.parseInt(txtDoctorTel.getText());
            DoctorDTO doctor=new DoctorDTO(DoctId, DoctName, DoctAddress, DoctIdCardNum, DoctHospital, DoctSpecialType, DoctTel,DoctName);
            boolean updateDoctor=DoctorController.updateDoctor(doctor);
            if(updateDoctor){
                getAllDoctors();
                clearAll();
                JOptionPane.showMessageDialog(this, "Update Doctor");
            }else{
                JOptionPane.showMessageDialog(this, "Failed");
            }
            
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnDoctorUpdateActionPerformed

    private void btnDoctorRefershActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorRefershActionPerformed
        clearAll();
        getAllDoctors();
    }//GEN-LAST:event_btnDoctorRefershActionPerformed

    private void btnusersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnusersActionPerformed
        new User().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnusersActionPerformed

    private void btnsheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsheduleActionPerformed

        new Shedule().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnsheduleActionPerformed

    private void btnspecialtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnspecialtypeActionPerformed
        new SpecialType().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnspecialtypeActionPerformed

    private void txtDoctorIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoctorIdActionPerformed
            String DoctorID=txtDoctorId.getText();
        try {
            clearAll();
            DoctorDTO searchDoctor=DoctorController.searchDoctor(DoctorID);
            txtDoctorId.setText(searchDoctor.getDoctId());
            txtDoctorName.setText(searchDoctor.getDoctName());
            txtDoctorAddress.setText(searchDoctor.getDoctAddress());
            txtDoctorIdCard.setText(searchDoctor.getDoctIdCardNum());
            txtDoctorHospital.setText(searchDoctor.getDoctHospital());
            txtDoctorSpecialtype.setText(searchDoctor.getDoctSpecialType());
            txtDoctorTel.setText(searchDoctor.getDoctTel()+"");
            txtDoctorGender.setText(searchDoctor.getDoctGende());
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtDoctorIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MangeDoctors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MangeDoctors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MangeDoctors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MangeDoctors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MangeDoctors().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoctorDelete;
    private javax.swing.JButton btnDoctorRefersh;
    private javax.swing.JButton btnDoctorSave;
    private javax.swing.JButton btnDoctorUpdate;
    private javax.swing.JButton btnshedule;
    private javax.swing.JButton btnspecialtype;
    private javax.swing.JButton btnusers;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lbltime;
    private javax.swing.JTable tblDoctorDetails;
    private javax.swing.JTextField txtDoctorAddress;
    private javax.swing.JTextField txtDoctorGender;
    private javax.swing.JTextField txtDoctorHospital;
    private javax.swing.JTextField txtDoctorId;
    private javax.swing.JTextField txtDoctorIdCard;
    private javax.swing.JTextField txtDoctorName;
    private javax.swing.JTextField txtDoctorSpecialtype;
    private javax.swing.JTextField txtDoctorTel;
    // End of variables declaration//GEN-END:variables

    private void clearAll() {
        txtDoctorId.setText("");
        txtDoctorName.setText("");
        txtDoctorAddress.setText("");
        txtDoctorIdCard.setText("");
        txtDoctorHospital.setText("");
        txtDoctorSpecialtype.setText("");
        txtDoctorTel.setText("");
        txtDoctorGender.setText("");
        txtDoctorId.requestFocus();
    }

    private void getAllDoctors() {
       try {
        dtm.setRowCount(0);
       
            ArrayList<DoctorDTO> allDoctors=DoctorController.getAllDoctor();
            for(DoctorDTO doct : allDoctors){
                Object[] rowData={doct.getDoctId(),doct.getDoctName(),doct.getDoctAddress(),doct.getDoctIdCardNum(),doct.getDoctHospital(),doct.getDoctSpecialType(),doct.getDoctTel(),doct.getDoctGende()};
                dtm.addRow(rowData);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MangeDoctors.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MangeDoctors.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }

    private boolean deleteDoctor(String DoctId) throws ClassNotFoundException, SQLException {
       return DoctorController.deleteDoctoor(DoctId);
    }

   private void autoSettime() {
       new Thread (new Runnable() {
            @Override
            public void run() {
                while(true){   
                    Date curDate = new Date();
                    SimpleDateFormat dateFormat =new SimpleDateFormat("HH:mm:ss:aa");
                    String currentTime =dateFormat.format(curDate);
                    lbltime.setText(currentTime);
                    try{
                        Thread.sleep(1000);
                    }catch(InterruptedException ex){
                        
                    }
                    
                }
            }
        }).start();
    }

    private void settDate() {
       lbldate.setText(LocalDate.now().toString()); 
    }

   
  
}
