/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.AppoinmentController;
import controller.PaymentController;
import dto.AppoinmentDTO;
import dto.PaymentDTO;
import entity.Appoinment;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Payment extends javax.swing.JFrame {

    private DefaultTableModel dtm;
    private DefaultTableModel dtmp;
    
    /**
     * Creates new form Payment
     */
    public Payment() {
        initComponents();
        autoSettime();
        settDate();
        dtm=(DefaultTableModel) tblAppoinmnet.getModel();
        getAllAppoinmnet();
        dtmp=(DefaultTableModel)tblpayement.getModel();
        getAllPayment();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtAppoinmnet = new javax.swing.JTextField();
        txtHospital = new javax.swing.JTextField();
        txtTotalAmount = new javax.swing.JTextField();
        txtDoctor = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblpayement = new javax.swing.JTable();
        lbldate = new javax.swing.JLabel();
        lbltime = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAppoinmnet = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        btnMake = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnrefresh = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(194, 216, 249));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/Card Payment_90px.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 100, 70));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel2.setText("MANAGE PAYMENT ");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/Home2_48px.png"))); // NOI18N
        jButton1.setText("HOME");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 17, 110, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 80));

        jPanel3.setBackground(new java.awt.Color(232, 228, 228));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/two.png"))); // NOI18N
        jLabel3.setText("Appoinment Number");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/two.png"))); // NOI18N
        jLabel5.setText("Hospital Charge");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/two.png"))); // NOI18N
        jLabel6.setText("Doctor Charge");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/two.png"))); // NOI18N
        jLabel7.setText("Total Amount");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/two.png"))); // NOI18N
        jLabel8.setText("Date");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        txtAppoinmnet.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtAppoinmnet.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtAppoinmnet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAppoinmnetActionPerformed(evt);
            }
        });
        jPanel3.add(txtAppoinmnet, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 240, 30));

        txtHospital.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtHospital.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHospitalActionPerformed(evt);
            }
        });
        jPanel3.add(txtHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, 260, 30));

        txtTotalAmount.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtTotalAmount.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtTotalAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalAmountActionPerformed(evt);
            }
        });
        jPanel3.add(txtTotalAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 80, 260, 30));

        txtDoctor.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtDoctor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoctorActionPerformed(evt);
            }
        });
        jPanel3.add(txtDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 240, 30));

        txtDate.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtDate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 240, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 1070, 230));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblpayement.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblpayement.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Appoinment Number", "Hospitala Charage", "Doctor Charge", "Total Amount", "Date"
            }
        ));
        tblpayement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpayementMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblpayement);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 60, 620, 260));

        lbldate.setBackground(new java.awt.Color(0, 0, 0));
        lbldate.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbldate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/Calendar_30px.png"))); // NOI18N
        lbldate.setText("Date");
        jPanel4.add(lbldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 290, 50));

        lbltime.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbltime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/Time_30px.png"))); // NOI18N
        lbltime.setText("time");
        jPanel4.add(lbltime, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 260, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 204));
        jLabel9.setText("Payment Details");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, 280, -1));

        tblAppoinmnet.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblAppoinmnet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Appoint ID", "Patient Name", "Patient NIC", "Doctor Name", "Description", "Date", "Sesion", "Patient Tel"
            }
        ));
        tblAppoinmnet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAppoinmnetMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblAppoinmnet);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 700, 260));

        jLabel4.setBackground(new java.awt.Color(0, 102, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 204));
        jLabel4.setText("Appoinment Details");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 320, 40));

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 0, 51));
        jButton6.setText("Print Bill");
        jButton6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 330, 110, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 1370, 380));

        btnMake.setBackground(new java.awt.Color(0, 102, 255));
        btnMake.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnMake.setText("MAKE PAYMENT");
        btnMake.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakeActionPerformed(evt);
            }
        });
        jPanel1.add(btnMake, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 90, 160, 50));

        btnUpdate.setBackground(new java.awt.Color(255, 255, 204));
        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnUpdate.setText("UPDATE PAYMENT");
        btnUpdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 180, 160, 50));

        btnrefresh.setBackground(new java.awt.Color(0, 153, 51));
        btnrefresh.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnrefresh.setText("REFRESH PAYMENT");
        btnrefresh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });
        jPanel1.add(btnrefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 270, 160, 50));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/Ok_60px.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 90, 60, 60));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/Delete_60px.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 180, 60, 50));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/Refresh_60px.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 270, 60, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new ReceptionDash().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtAppoinmnetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAppoinmnetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAppoinmnetActionPerformed

    private void txtDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoctorActionPerformed
        txtTotalAmount.requestFocus();
    }//GEN-LAST:event_txtDoctorActionPerformed

    private void tblAppoinmnetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAppoinmnetMouseClicked
        int selectedRow=tblAppoinmnet.getSelectedRow();
        String id=dtm.getValueAt(selectedRow, 0).toString();
        txtAppoinmnet.setText(id);

    }//GEN-LAST:event_tblAppoinmnetMouseClicked

    private void btnMakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakeActionPerformed
        try {
            String AppoinmtNum=txtAppoinmnet.getText();
            double HospiChage=Double.parseDouble(txtHospital.getText());
            double DoctCharege=Double.parseDouble(txtDoctor.getText());
            double Total=Double.parseDouble(txtTotalAmount.getText());
            String Date=txtDate.getText();
            
            PaymentDTO paymentModel = new PaymentDTO(AppoinmtNum, HospiChage, DoctCharege, Total, Date);
            boolean addPayement=PaymentController.addPayment(paymentModel);
            if(addPayement){
                JOptionPane.showMessageDialog(this, "Make Payment");
                clearAll();
                getAllPayment();
            }else{
                JOptionPane.showMessageDialog(this, "Failed");
            }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnMakeActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
            
        try {
            String AppoinmtNum=txtAppoinmnet.getText();
            double HospiChage=Double.parseDouble(txtHospital.getText());
            double DoctCharege=Double.parseDouble(txtDoctor.getText());
            double Total=Double.parseDouble(txtTotalAmount.getText());
            String Date=txtDate.getText();
            
            PaymentDTO paymentModel = new PaymentDTO(AppoinmtNum, HospiChage, DoctCharege, Total, Date);
            boolean updatePayment=new PaymentController().updatePayment(paymentModel);
            if(updatePayment){
               getAllPayment();
               clearAll();
               JOptionPane.showMessageDialog(this, "Updated Payment");
            }else{
                JOptionPane.showMessageDialog(this, "Failed");
            }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
        clearAll();
        getAllPayment();
    }//GEN-LAST:event_btnrefreshActionPerformed

    private void tblpayementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpayementMouseClicked
      int selectedRow=tblpayement.getSelectedRow();
        String appNum=dtmp.getValueAt(selectedRow, 0).toString();
        String hosCharge=dtmp.getValueAt(selectedRow, 1).toString();
        String doctChareg=dtmp.getValueAt(selectedRow, 2).toString();
        String total=dtmp.getValueAt(selectedRow, 3).toString();
        String date=dtmp.getValueAt(selectedRow, 4).toString();
        txtAppoinmnet.setText(appNum);
        txtHospital.setText(hosCharge);
        txtDoctor.setText(doctChareg);
        txtTotalAmount.setText(total);
        txtDate.setText(date);
    }//GEN-LAST:event_tblpayementMouseClicked

    private void txtHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHospitalActionPerformed
       txtDoctor.requestFocus();
    }//GEN-LAST:event_txtHospitalActionPerformed

    private void txtTotalAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalAmountActionPerformed
        btnMake.requestFocus();
        btnMake.doClick();
    }//GEN-LAST:event_txtTotalAmountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMake;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lbltime;
    private javax.swing.JTable tblAppoinmnet;
    private javax.swing.JTable tblpayement;
    private javax.swing.JTextField txtAppoinmnet;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDoctor;
    private javax.swing.JTextField txtHospital;
    private javax.swing.JTextField txtTotalAmount;
    // End of variables declaration//GEN-END:variables

private void autoSettime() {
       new Thread (new Runnable() {
            @Override
            public void run() {
                while(true){   
                    Date curDate = new Date();
                    SimpleDateFormat dateFormat =new SimpleDateFormat("HH:mm:ss:aa");
                    String currentTime =dateFormat.format(curDate);
                    lbltime.setText(currentTime);
                    try{
                        Thread.sleep(1000);
                    }catch(InterruptedException ex){
                        
                    }
                    
                }
            }
        }).start();
    }

    private void settDate() {
       lbldate.setText(LocalDate.now().toString()); 
       txtDate.setText(LocalDate.now().toString());
    }

//    private void getAllAppoinmnet() {
//        try {
//
//            dtm.setRowCount(0);
//            ArrayList<AppoinmentDTO> allCustomers = AppoinmentController.getAllAppoinment();
//            for (AppoinmentDTO app : allCustomers) {
//                Object[] rowData={app.getAppoinmentNum(),app.getPatientName(),app.getPatientId(),app.getDoctorName(),app.getDescription(),app.getAppoinmentdate(),app.getShedule(),app.getPatientTel()};
//                dtm.addRow(rowData);
//            }
//        } catch (SQLException ex) {
//            Logger.getLogger(Apponmnet.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (ClassNotFoundException ex) {
//            Logger.getLogger(Apponmnet.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }

     private void getAllAppoinmnet() {
      try {
          dtm.setRowCount(0);
          ArrayList<AppoinmentDTO> allAppoinment=AppoinmentController.getAllAppoinment();
          for(AppoinmentDTO app:allAppoinment){
              Object[] rowData={app.getAppoinmentNum(),app.getPatientName(),app.getPatientId(),app.getDoctorName(),app.getDescription(),app.getAppoinmentdate(),app.getShedule(),app.getPatientTel()};
              dtm.addRow(rowData);
          }
          
      } catch (ClassNotFoundException ex) {
          Logger.getLogger(Apponmnet.class.getName()).log(Level.SEVERE, null, ex);
      } catch (SQLException ex) {
          Logger.getLogger(Apponmnet.class.getName()).log(Level.SEVERE, null, ex);
      }
    }
    
    private void clearAll() {
       txtAppoinmnet.setText("");
       txtHospital.setText("");
       txtDoctor.setText("");
       txtTotalAmount.setText("");
       txtDate.setText("");
    }

    private void getAllPayment() {
        try {
            dtmp.setRowCount(0);
            ArrayList<PaymentDTO> allPayment=PaymentController.getAllPayment();
            for(PaymentDTO pay:allPayment){
                Object[] rowData={pay.getAppoinmnetNum(),pay.getHospitalaCharge(),pay.getDoctorCharge(),pay.getTotal(),pay.getDate()};
                dtmp.addRow(rowData);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    
}
