/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.custom.QueryDAO;
import dao.custom.impl.QueryDAOImpl;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;

/**
 *
 * @author User
 */
public class ReceptionDash extends javax.swing.JFrame {

    QueryDAO queryDAO=new QueryDAOImpl();
    
    /**
     * Creates new form ReceptionDash
     */
    public ReceptionDash() {
       initComponents();
       pnl4.setBackground(new java.awt.Color(0,0,0,170));
       pnl5.setBackground(new java.awt.Color(0,0,0,170));
       pnl6.setBackground(new java.awt.Color(0,0,0,170));
       pnl8.setBackground(new java.awt.Color(0,0,0,170));
       pnl7.setBackground(new java.awt.Color(0,0,0,170));
       
       autoSettime();
       settDate();
       getCount();
       getCounttwo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar2 = new com.toedter.calendar.JCalendar();
        jPanel1 = new javax.swing.JPanel();
        btnadmindoct = new javax.swing.JButton();
        btnadminshedule = new javax.swing.JButton();
        btnadminapecialtype = new javax.swing.JButton();
        btmadminusers = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnadmindoct1 = new javax.swing.JButton();
        btmadminusers1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        pnl6 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        pnl5 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        pnl7 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        pnl4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        pnl8 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblcountdoct = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblcountApp = new javax.swing.JLabel();
        lbldate1 = new javax.swing.JLabel();
        lbltime = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnadmindoct.setBackground(new java.awt.Color(204, 204, 204));
        btnadmindoct.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        btnadmindoct.setText("Appoinment");
        btnadmindoct.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnadmindoct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnadmindoctMouseClicked(evt);
            }
        });
        btnadmindoct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadmindoctActionPerformed(evt);
            }
        });
        jPanel1.add(btnadmindoct, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 170, 50));

        btnadminshedule.setBackground(new java.awt.Color(204, 204, 204));
        btnadminshedule.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        btnadminshedule.setText("Payment");
        btnadminshedule.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnadminshedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadminsheduleActionPerformed(evt);
            }
        });
        jPanel1.add(btnadminshedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 170, 50));

        btnadminapecialtype.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        btnadminapecialtype.setText("Shedule");
        btnadminapecialtype.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnadminapecialtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadminapecialtypeActionPerformed(evt);
            }
        });
        jPanel1.add(btnadminapecialtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 170, 50));

        btmadminusers.setBackground(new java.awt.Color(204, 204, 204));
        btmadminusers.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        btmadminusers.setText("Special Types");
        btmadminusers.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btmadminusers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmadminusersActionPerformed(evt);
            }
        });
        jPanel1.add(btmadminusers, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 170, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 305)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setText("+");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -40, 250, 260));

        btnadmindoct1.setBackground(new java.awt.Color(204, 204, 204));
        btnadmindoct1.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        btnadmindoct1.setText("Doctors");
        btnadmindoct1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnadmindoct1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnadmindoct1MouseClicked(evt);
            }
        });
        btnadmindoct1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadmindoct1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnadmindoct1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 170, 50));

        btmadminusers1.setBackground(new java.awt.Color(204, 204, 204));
        btmadminusers1.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        btmadminusers1.setText("Users");
        btmadminusers1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btmadminusers1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmadminusers1ActionPerformed(evt);
            }
        });
        jPanel1.add(btmadminusers1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 650, 170, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 710));

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/Logout Rounded Left_24px.png"))); // NOI18N
        jButton1.setText("Log Out");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 30, 110, 40));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("DURDANS HOSPITAL");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 850, 80));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 1150, 80));

        pnl6.setBackground(new java.awt.Color(0, 0, 0));
        pnl6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/Timesheet_96px.png"))); // NOI18N
        jButton4.setText("SHEDULE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        pnl6.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 280, 100));

        getContentPane().add(pnl6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 510, 380, 160));

        pnl5.setBackground(new java.awt.Color(0, 0, 0));
        pnl5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/Cash in Hand_96px.png"))); // NOI18N
        jButton3.setText("PAYMNET");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        pnl5.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 280, 90));

        getContentPane().add(pnl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, 370, 160));

        pnl7.setBackground(new java.awt.Color(0, 0, 0));
        pnl7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/Join_96px.png"))); // NOI18N
        jButton5.setText("SEPECIALISTS");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        pnl7.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 270, 100));

        getContentPane().add(pnl7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 510, 360, 160));

        pnl4.setBackground(new java.awt.Color(0, 0, 0));
        pnl4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/Hand With Pen_96px.png"))); // NOI18N
        jButton2.setText("APPOINMNETS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        pnl4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 280, 100));

        getContentPane().add(pnl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 380, 160));

        pnl8.setBackground(new java.awt.Color(0, 0, 0));
        pnl8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/Doctor Male_96px.png"))); // NOI18N
        jButton6.setText("MANAGE DOCTOR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        pnl8.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 300, 100));

        getContentPane().add(pnl8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 400, 160));

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 40)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Doctors");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 190, 150, 40));

        lblcountdoct.setFont(new java.awt.Font("Tahoma", 1, 75)); // NOI18N
        lblcountdoct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcountdoct.setText("00");
        getContentPane().add(lblcountdoct, new org.netbeans.lib.awtextra.AbsoluteConstraints(1147, 240, 110, 70));

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 40)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Appoinments");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 430, 250, -1));

        lblcountApp.setFont(new java.awt.Font("Tahoma", 1, 75)); // NOI18N
        lblcountApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcountApp.setText("00");
        getContentPane().add(lblcountApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 480, 130, 70));

        lbldate1.setBackground(new java.awt.Color(0, 0, 0));
        lbldate1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbldate1.setForeground(new java.awt.Color(0, 102, 204));
        lbldate1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/Calendar_30px.png"))); // NOI18N
        lbldate1.setText("Date");
        getContentPane().add(lbldate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 596, 260, -1));

        lbltime.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbltime.setForeground(new java.awt.Color(0, 102, 204));
        lbltime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/Time_30px.png"))); // NOI18N
        lbltime.setText("time");
        getContentPane().add(lbltime, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 660, 250, 40));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/Doctor Female_96px.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 90, 120, 90));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/Hand With Pen_96px.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 330, 120, 100));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/123.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lbldate.setBackground(new java.awt.Color(0, 0, 0));
        lbldate.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbldate.setForeground(new java.awt.Color(0, 102, 204));
        lbldate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/Calendar_30px.png"))); // NOI18N
        lbldate.setText("Date");
        jPanel3.add(lbldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 596, 260, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 1150, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnadmindoctMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnadmindoctMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_btnadmindoctMouseClicked

    private void btnadmindoctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadmindoctActionPerformed
        new Apponmnet().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnadmindoctActionPerformed

    private void btnadminsheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadminsheduleActionPerformed
        new Payment().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnadminsheduleActionPerformed

    private void btnadminapecialtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadminapecialtypeActionPerformed
        new Shedule().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnadminapecialtypeActionPerformed

    private void btmadminusersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmadminusersActionPerformed
        new SpecialType().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btmadminusersActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Loginframe().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Apponmnet().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new Payment().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new SpecialType().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new Shedule().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnadmindoct1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnadmindoct1MouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_btnadmindoct1MouseClicked

    private void btnadmindoct1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadmindoct1ActionPerformed
        new MangeDoctors().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnadmindoct1ActionPerformed

    private void btmadminusers1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmadminusers1ActionPerformed
        new User().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btmadminusers1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        new MangeDoctors().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReceptionDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReceptionDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReceptionDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReceptionDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReceptionDash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmadminusers;
    private javax.swing.JButton btmadminusers1;
    private javax.swing.JButton btnadminapecialtype;
    private javax.swing.JButton btnadmindoct;
    private javax.swing.JButton btnadmindoct1;
    private javax.swing.JButton btnadminshedule;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private com.toedter.calendar.JCalendar jCalendar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblcountApp;
    private javax.swing.JLabel lblcountdoct;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lbldate1;
    private javax.swing.JLabel lbltime;
    private javax.swing.JPanel pnl4;
    private javax.swing.JPanel pnl5;
    private javax.swing.JPanel pnl6;
    private javax.swing.JPanel pnl7;
    private javax.swing.JPanel pnl8;
    // End of variables declaration//GEN-END:variables

private void autoSettime() {
       new Thread (new Runnable() {
            @Override
            public void run() {
                while(true){   
                    Date curDate = new Date();
                    SimpleDateFormat dateFormat =new SimpleDateFormat("HH:mm:ss:aa");
                    String currentTime =dateFormat.format(curDate);
                    lbltime.setText(currentTime);
                    try{
                        Thread.sleep(1000);
                    }catch(InterruptedException ex){
                        
                    }
                    
                }
            }
        }).start();
    }

    private void settDate() {
       lbldate1.setText(LocalDate.now().toString()); 
    }
    
    
    private void getCount() {
       int row=queryDAO.rowCount();
       lblcountdoct.setText(row+"");
    }

    private void getCounttwo() {
       int row=queryDAO.rowCounttwo();
       lblcountApp.setText(row+"");
    }
}
