/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.SheduleController;
import dto.SheduleDTO;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Shedule extends javax.swing.JFrame {

    private DefaultTableModel dtm;
    
    
    public Shedule() {
        initComponents();
        dtm=(DefaultTableModel)tblSheduleDetails.getModel();
        getAllShedule();
        autoSettime();
        settDate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnshedule = new javax.swing.JButton();
        btnspecialtype = new javax.swing.JButton();
        btnusers = new javax.swing.JButton();
        btnshedule1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtShedDoctId = new javax.swing.JTextField();
        txtShedDoctName = new javax.swing.JTextField();
        txtShedMonday = new javax.swing.JTextField();
        txtShedThursday = new javax.swing.JTextField();
        txtShedFriday = new javax.swing.JTextField();
        txtShedWednessday = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtShedTuesday = new javax.swing.JTextField();
        txtShedSaturday = new javax.swing.JTextField();
        txtShedSunday = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSheduleDetails = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();
        lbltime = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnshedsave = new javax.swing.JButton();
        btnshedupdate = new javax.swing.JButton();
        btnshedrefresh = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(194, 216, 249));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/Calendar_60px.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 80));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel1.setText("MANAGE SHEDULE");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 470, 60));

        btnshedule.setBackground(new java.awt.Color(0, 0, 153));
        btnshedule.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnshedule.setForeground(new java.awt.Color(255, 255, 255));
        btnshedule.setText("DOCTORS");
        btnshedule.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnshedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsheduleActionPerformed(evt);
            }
        });
        jPanel2.add(btnshedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, 110, 50));

        btnspecialtype.setBackground(new java.awt.Color(0, 0, 153));
        btnspecialtype.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnspecialtype.setForeground(new java.awt.Color(255, 255, 255));
        btnspecialtype.setText("SPECIAL TYPE");
        btnspecialtype.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnspecialtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnspecialtypeActionPerformed(evt);
            }
        });
        jPanel2.add(btnspecialtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, 110, 50));

        btnusers.setBackground(new java.awt.Color(0, 0, 153));
        btnusers.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnusers.setForeground(new java.awt.Color(255, 255, 255));
        btnusers.setText("USERS");
        btnusers.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnusers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnusersActionPerformed(evt);
            }
        });
        jPanel2.add(btnusers, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, 110, 50));

        btnshedule1.setBackground(new java.awt.Color(0, 0, 153));
        btnshedule1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnshedule1.setForeground(new java.awt.Color(255, 255, 255));
        btnshedule1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/Home1_48px.png"))); // NOI18N
        btnshedule1.setText("HOME");
        btnshedule1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnshedule1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshedule1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnshedule1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 10, 110, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 80));

        jPanel4.setBackground(new java.awt.Color(232, 228, 228));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/two.png"))); // NOI18N
        jLabel5.setText("Doctor ID");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/two.png"))); // NOI18N
        jLabel16.setText("Doctor Name");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/two.png"))); // NOI18N
        jLabel17.setText("Monday");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/two.png"))); // NOI18N
        jLabel18.setText("Thursday");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/two.png"))); // NOI18N
        jLabel19.setText("Tuesday");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/two.png"))); // NOI18N
        jLabel20.setText("Wednesday");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/two.png"))); // NOI18N
        jLabel21.setText("Friday");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        txtShedDoctId.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtShedDoctId.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtShedDoctId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtShedDoctIdActionPerformed(evt);
            }
        });
        jPanel4.add(txtShedDoctId, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 230, 30));

        txtShedDoctName.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtShedDoctName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtShedDoctName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtShedDoctNameActionPerformed(evt);
            }
        });
        jPanel4.add(txtShedDoctName, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 240, 30));

        txtShedMonday.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtShedMonday.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtShedMonday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtShedMondayActionPerformed(evt);
            }
        });
        jPanel4.add(txtShedMonday, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 230, 30));

        txtShedThursday.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtShedThursday.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtShedThursday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtShedThursdayActionPerformed(evt);
            }
        });
        jPanel4.add(txtShedThursday, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 130, 240, 30));

        txtShedFriday.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtShedFriday.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtShedFriday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtShedFridayActionPerformed(evt);
            }
        });
        jPanel4.add(txtShedFriday, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 230, 30));

        txtShedWednessday.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtShedWednessday.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtShedWednessday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtShedWednessdayActionPerformed(evt);
            }
        });
        jPanel4.add(txtShedWednessday, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 230, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/two.png"))); // NOI18N
        jLabel2.setText("Sunday");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 130, 40));

        txtShedTuesday.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtShedTuesday.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtShedTuesday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtShedTuesdayActionPerformed(evt);
            }
        });
        jPanel4.add(txtShedTuesday, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 68, 240, 30));

        txtShedSaturday.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtShedSaturday.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtShedSaturday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtShedSaturdayActionPerformed(evt);
            }
        });
        jPanel4.add(txtShedSaturday, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 188, 240, 30));

        txtShedSunday.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtShedSunday.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtShedSunday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtShedSundayActionPerformed(evt);
            }
        });
        jPanel4.add(txtShedSunday, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 248, 230, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/two.png"))); // NOI18N
        jLabel6.setText("Saturday");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 1030, 300));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblSheduleDetails.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblSheduleDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Doctor ID", "Doctor Name", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"
            }
        ));
        tblSheduleDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSheduleDetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSheduleDetails);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1030, 230));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Shedule Details");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 270, 40));

        lbldate.setBackground(new java.awt.Color(0, 0, 0));
        lbldate.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbldate.setForeground(new java.awt.Color(0, 51, 204));
        lbldate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/Calendar_30px.png"))); // NOI18N
        lbldate.setText("Date");
        jPanel3.add(lbldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 290, 40));

        lbltime.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbltime.setForeground(new java.awt.Color(0, 51, 204));
        lbltime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/Time_30px.png"))); // NOI18N
        lbltime.setText("time");
        jPanel3.add(lbltime, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 260, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 1030, 310));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnshedsave.setBackground(new java.awt.Color(0, 102, 255));
        btnshedsave.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnshedsave.setText("SAVE SHEDULE");
        btnshedsave.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnshedsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshedsaveActionPerformed(evt);
            }
        });
        jPanel5.add(btnshedsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 190, 50));

        btnshedupdate.setBackground(new java.awt.Color(255, 255, 204));
        btnshedupdate.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnshedupdate.setText("UPDATE SHEDULE");
        btnshedupdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnshedupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshedupdateActionPerformed(evt);
            }
        });
        jPanel5.add(btnshedupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 190, 50));

        btnshedrefresh.setBackground(new java.awt.Color(0, 153, 51));
        btnshedrefresh.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnshedrefresh.setText("REFRESH SHEDULE");
        btnshedrefresh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnshedrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshedrefreshActionPerformed(evt);
            }
        });
        jPanel5.add(btnshedrefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 190, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/Ok_60px.png"))); // NOI18N
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 60));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/Update_60px.png"))); // NOI18N
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 70, 60));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/Refresh_60px.png"))); // NOI18N
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 60, 50));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 90, 310, 210));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/bright-cardiac-cardiology-433267.jpg"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 320, 310, 370));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtShedDoctNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtShedDoctNameActionPerformed
        txtShedMonday.requestFocus();
    }//GEN-LAST:event_txtShedDoctNameActionPerformed

    private void txtShedMondayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtShedMondayActionPerformed
        txtShedTuesday.requestFocus();
    }//GEN-LAST:event_txtShedMondayActionPerformed

    private void txtShedTuesdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtShedTuesdayActionPerformed
        txtShedWednessday.requestFocus();
    }//GEN-LAST:event_txtShedTuesdayActionPerformed

    private void txtShedWednessdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtShedWednessdayActionPerformed
        txtShedThursday.requestFocus();
    }//GEN-LAST:event_txtShedWednessdayActionPerformed

    private void txtShedThursdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtShedThursdayActionPerformed
        txtShedFriday.requestFocus();
    }//GEN-LAST:event_txtShedThursdayActionPerformed

    private void txtShedFridayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtShedFridayActionPerformed
        txtShedSaturday.requestFocus();
    }//GEN-LAST:event_txtShedFridayActionPerformed

    private void txtShedSaturdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtShedSaturdayActionPerformed
        txtShedSunday.requestFocus();
    }//GEN-LAST:event_txtShedSaturdayActionPerformed

    private void txtShedSundayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtShedSundayActionPerformed
        btnshedsave.requestFocus();
        btnshedsave.doClick();
    }//GEN-LAST:event_txtShedSundayActionPerformed

    private void btnshedsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshedsaveActionPerformed

        try {
            String DoctId=txtShedDoctId.getText();
            String DoctName=txtShedDoctName.getText();
            String ShedMon=txtShedMonday.getText();
            String ShedTue=txtShedTuesday.getText();
            String ShedWed=txtShedWednessday.getText();
            String ShedThu=txtShedThursday.getText();
            String ShedFri=txtShedFriday.getText();
            String ShedSat=txtShedSaturday.getText();
            String ShedSun=txtShedSunday.getText();
            
            SheduleDTO shedModel = new SheduleDTO(DoctId, DoctName, ShedMon, ShedTue, ShedWed, ShedThu, ShedFri, ShedSat, ShedSun);
            boolean addShedule=SheduleController.addShedule(shedModel);
            if(addShedule){
                JOptionPane.showMessageDialog(this, "Added");
                clearAll();
                getAllShedule();
            }else{
                JOptionPane.showMessageDialog(this, "Failed");
            }
            
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnshedsaveActionPerformed

    private void tblSheduleDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSheduleDetailsMouseClicked
        int selectedRow=tblSheduleDetails.getSelectedRow();
        String DoctId=dtm.getValueAt(selectedRow, 0).toString();
        String DoctName=dtm.getValueAt(selectedRow, 1).toString();
        String ShedMon =dtm.getValueAt(selectedRow, 2).toString();
        String ShedTue =dtm.getValueAt(selectedRow, 3).toString();
        String ShedWed =dtm.getValueAt(selectedRow, 4).toString();
        String ShedThu =dtm.getValueAt(selectedRow, 5).toString();
        String ShedFri =dtm.getValueAt(selectedRow, 6).toString();
        String ShedSat =dtm.getValueAt(selectedRow, 7).toString();
        String ShedSun =dtm.getValueAt(selectedRow, 8).toString();
        txtShedDoctId.setText(DoctId);
        txtShedDoctName.setText(DoctName);
        txtShedMonday.setText(ShedMon);
        txtShedTuesday.setText(ShedTue);
        txtShedWednessday.setText(ShedWed);
        txtShedThursday.setText(ShedThu);
        txtShedFriday.setText(ShedFri);
        txtShedSaturday.setText(ShedSat);
        txtShedSunday.setText(ShedSun);
    }//GEN-LAST:event_tblSheduleDetailsMouseClicked

    private void btnshedupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshedupdateActionPerformed

        try {
            String DoctId=txtShedDoctId.getText();
            String DoctName=txtShedDoctName.getText();
            String ShedMon=txtShedMonday.getText();
            String ShedTue=txtShedTuesday.getText();
            String ShedWed=txtShedWednessday.getText();
            String ShedThu=txtShedThursday.getText();
            String ShedFri=txtShedFriday.getText();
            String ShedSat=txtShedSaturday.getText();
            String ShedSun=txtShedSunday.getText();
            SheduleDTO shedModel = new SheduleDTO(DoctId, DoctName, ShedMon, ShedTue, ShedWed, ShedThu, ShedFri, ShedSat, ShedSun);
            boolean updateShedule=SheduleController.updateShedule(shedModel);
            if(updateShedule){
                getAllShedule();
                clearAll();
                JOptionPane.showMessageDialog(this, "Updated");
            }else{
                JOptionPane.showMessageDialog(this, "Failed");
            }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnshedupdateActionPerformed

    private void btnshedrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshedrefreshActionPerformed
        clearAll();
        getAllShedule();
    }//GEN-LAST:event_btnshedrefreshActionPerformed

    private void btnsheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsheduleActionPerformed
        
        new MangeDoctors().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnsheduleActionPerformed

    private void btnspecialtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnspecialtypeActionPerformed
        new SpecialType().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnspecialtypeActionPerformed

    private void btnusersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnusersActionPerformed
        new User().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnusersActionPerformed

    private void txtShedDoctIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtShedDoctIdActionPerformed

       String DoctId=txtShedDoctId.getText();
        try {
            clearAll();
            SheduleDTO searchShedule=SheduleController.searchShedule(DoctId);
            txtShedDoctId.setText(searchShedule.getDoctId());
            txtShedDoctName.setText(searchShedule.getDoctName());
            txtShedMonday.setText(searchShedule.getShedMon());
            txtShedTuesday.setText(searchShedule.getShedTue());
            txtShedWednessday.setText(searchShedule.getShedWed());
            txtShedThursday.setText(searchShedule.getShedThu());
            txtShedFriday.setText(searchShedule.getShedFri());
            txtShedSaturday.setText(searchShedule.getShedSat());
            txtShedSunday.setText(searchShedule.getShedSun());
        } catch (SQLException ex) {
            Logger.getLogger(Shedule.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Shedule.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtShedDoctIdActionPerformed

    private void btnshedule1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshedule1ActionPerformed
        new ReceptionDash().setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_btnshedule1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Shedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Shedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Shedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Shedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Shedule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnshedrefresh;
    private javax.swing.JButton btnshedsave;
    private javax.swing.JButton btnshedule;
    private javax.swing.JButton btnshedule1;
    private javax.swing.JButton btnshedupdate;
    private javax.swing.JButton btnspecialtype;
    private javax.swing.JButton btnusers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lbltime;
    private javax.swing.JTable tblSheduleDetails;
    private javax.swing.JTextField txtShedDoctId;
    private javax.swing.JTextField txtShedDoctName;
    private javax.swing.JTextField txtShedFriday;
    private javax.swing.JTextField txtShedMonday;
    private javax.swing.JTextField txtShedSaturday;
    private javax.swing.JTextField txtShedSunday;
    private javax.swing.JTextField txtShedThursday;
    private javax.swing.JTextField txtShedTuesday;
    private javax.swing.JTextField txtShedWednessday;
    // End of variables declaration//GEN-END:variables

    private void clearAll() {
        txtShedDoctId.setText("");
        txtShedDoctName.setText("");
        txtShedMonday.setText("");
        txtShedTuesday.setText("");
        txtShedWednessday.setText("");
        txtShedThursday.setText("");
        txtShedFriday.setText("");
        txtShedSaturday.setText("");
        txtShedSunday.setText("");
   }

    private void getAllShedule() {
        try {
            dtm.setRowCount(0);
            ArrayList<SheduleDTO> allShedule=SheduleController.getAllShedule();
            for(SheduleDTO shed:allShedule){
                Object[] rowData={shed.getDoctId(),shed.getDoctName(),shed.getShedMon(),shed.getShedTue(),shed.getShedWed(),shed.getShedThu(),shed.getShedFri(),shed.getShedSat(),shed.getShedSun()};
                dtm.addRow(rowData);
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Shedule.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Shedule.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void autoSettime() {
       new Thread (new Runnable() {
            @Override
            public void run() {
                while(true){   
                    Date curDate = new Date();
                    SimpleDateFormat dateFormat =new SimpleDateFormat("HH:mm:ss:aa");
                    String currentTime =dateFormat.format(curDate);
                    lbltime.setText(currentTime);
                    try{
                        Thread.sleep(1000);
                    }catch(InterruptedException ex){
                        
                    }
                    
                }
            }
        }).start();
    }

    private void settDate() {
       lbldate.setText(LocalDate.now().toString()); 
    }

}
