/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.DoctorController;
import controller.SpecialtypeController;
import dao.DAOFactory;
import dao.custom.SpecialtypeDAO;
import dto.DoctorDTO;
import dto.SpecialtypeDTO;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author User
 */
public class SpecialType extends javax.swing.JFrame {

    private DefaultTableModel dtm;
    
    /**
     * Creates new form SpecialType
     */
    public SpecialType() {
        initComponents();
        dtm= (DefaultTableModel)tblspeciatypeDetailsl.getModel();
        getAllSpecialtype();
        autoSettime();
        settDate();
//        pnl5.setBackground(new java.awt.Color(225,219,215,125));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnshedule = new javax.swing.JButton();
        btnspecialtype = new javax.swing.JButton();
        btnusers = new javax.swing.JButton();
        btnshedule1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtspecialDoctId = new javax.swing.JTextField();
        txtspecialDoctname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtspecialDescription = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblspeciatypeDetailsl = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnSpecialRefresh = new javax.swing.JButton();
        pnl5 = new javax.swing.JPanel();
        lbltime = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(194, 216, 249));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/Search_60px.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 80));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel1.setText("SEARCH SPECIAL TYPES");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 620, 60));

        btnshedule.setBackground(new java.awt.Color(0, 0, 153));
        btnshedule.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnshedule.setForeground(new java.awt.Color(255, 255, 255));
        btnshedule.setText("DOCTORS");
        btnshedule.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnshedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsheduleActionPerformed(evt);
            }
        });
        jPanel2.add(btnshedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, 110, 50));

        btnspecialtype.setBackground(new java.awt.Color(0, 0, 153));
        btnspecialtype.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnspecialtype.setForeground(new java.awt.Color(255, 255, 255));
        btnspecialtype.setText("SHEDULE");
        btnspecialtype.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnspecialtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnspecialtypeActionPerformed(evt);
            }
        });
        jPanel2.add(btnspecialtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 10, 110, 50));

        btnusers.setBackground(new java.awt.Color(0, 0, 153));
        btnusers.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnusers.setForeground(new java.awt.Color(255, 255, 255));
        btnusers.setText("USERS");
        btnusers.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnusers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnusersActionPerformed(evt);
            }
        });
        jPanel2.add(btnusers, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 10, 110, 50));

        btnshedule1.setBackground(new java.awt.Color(0, 0, 153));
        btnshedule1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnshedule1.setForeground(new java.awt.Color(255, 255, 255));
        btnshedule1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/Home1_48px.png"))); // NOI18N
        btnshedule1.setText("HOME");
        btnshedule1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnshedule1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshedule1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnshedule1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, 110, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 80));

        jPanel4.setBackground(new java.awt.Color(232, 228, 228));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/two.png"))); // NOI18N
        jLabel16.setText("Doctor ID");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/two.png"))); // NOI18N
        jLabel17.setText("Doctor Name");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, -1));

        txtspecialDoctId.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtspecialDoctId.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtspecialDoctId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtspecialDoctIdActionPerformed(evt);
            }
        });
        jPanel4.add(txtspecialDoctId, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 230, 30));

        txtspecialDoctname.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtspecialDoctname.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtspecialDoctname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtspecialDoctnameActionPerformed(evt);
            }
        });
        jPanel4.add(txtspecialDoctname, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 650, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/two.png"))); // NOI18N
        jLabel2.setText("Description");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 170, 40));

        txtspecialDescription.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtspecialDescription.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtspecialDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtspecialDescriptionActionPerformed(evt);
            }
        });
        jPanel4.add(txtspecialDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 970, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 1350, 140));

        jPanel3.setBackground(new java.awt.Color(232, 228, 228));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblspeciatypeDetailsl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblspeciatypeDetailsl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Doctor ID", "Doctor Name", "Description"
            }
        ));
        tblspeciatypeDetailsl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblspeciatypeDetailslMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblspeciatypeDetailsl);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 1330, 330));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Special Type Details");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 340, 40));

        btnSpecialRefresh.setBackground(new java.awt.Color(0, 153, 51));
        btnSpecialRefresh.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnSpecialRefresh.setText("REFRESH");
        btnSpecialRefresh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSpecialRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpecialRefreshActionPerformed(evt);
            }
        });
        jPanel3.add(btnSpecialRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 400, 100, 50));

        pnl5.setBackground(new java.awt.Color(232, 228, 228));
        pnl5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbltime.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbltime.setForeground(new java.awt.Color(0, 51, 204));
        lbltime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/Time_30px.png"))); // NOI18N
        lbltime.setText("time");
        pnl5.add(lbltime, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 290, -1));

        lbldate.setBackground(new java.awt.Color(0, 0, 0));
        lbldate.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbldate.setForeground(new java.awt.Color(0, 51, 204));
        lbldate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/Calendar_30px.png"))); // NOI18N
        lbldate.setText("Date");
        pnl5.add(lbldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 270, 40));

        jPanel3.add(pnl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 710, 50));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 1350, 460));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSpecialRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpecialRefreshActionPerformed
        clearAll();
        getAllSpecialtype();
    }//GEN-LAST:event_btnSpecialRefreshActionPerformed

    private void tblspeciatypeDetailslMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblspeciatypeDetailslMouseClicked
            int selectedRow=tblspeciatypeDetailsl.getSelectedRow();
            String DoctId =dtm.getValueAt(selectedRow, 0).toString();
            String DoctName=dtm.getValueAt(selectedRow,1).toString();
            String Description=dtm.getValueAt(selectedRow,2).toString();
            txtspecialDoctId.setText(DoctId);
            txtspecialDoctname.setText(DoctName);
            txtspecialDescription.setText(Description);
    }//GEN-LAST:event_tblspeciatypeDetailslMouseClicked

    private void btnsheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsheduleActionPerformed

        new MangeDoctors().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnsheduleActionPerformed

    private void btnspecialtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnspecialtypeActionPerformed
        new Shedule().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnspecialtypeActionPerformed

    private void btnusersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnusersActionPerformed
        new User().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnusersActionPerformed

    private void txtspecialDoctIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtspecialDoctIdActionPerformed
        String DoctId=txtspecialDoctId.getText();
        try {
            clearAll();

              DoctorDTO searchSpecialtype=DoctorController.searchDoctor(DoctId);
            txtspecialDoctId.setText(searchSpecialtype.getDoctId());
            txtspecialDoctname.setText(searchSpecialtype.getDoctName());
            txtspecialDescription.setText(searchSpecialtype.getDoctSpecialType());
        } catch (SQLException ex) {
            Logger.getLogger(SpecialType.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SpecialType.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtspecialDoctIdActionPerformed

    private void txtspecialDoctnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtspecialDoctnameActionPerformed
        
        
    }//GEN-LAST:event_txtspecialDoctnameActionPerformed

    private void txtspecialDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtspecialDescriptionActionPerformed
        
    }//GEN-LAST:event_txtspecialDescriptionActionPerformed

    private void btnshedule1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshedule1ActionPerformed
        new ReceptionDash().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnshedule1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SpecialType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SpecialType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SpecialType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SpecialType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SpecialType().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSpecialRefresh;
    private javax.swing.JButton btnshedule;
    private javax.swing.JButton btnshedule1;
    private javax.swing.JButton btnspecialtype;
    private javax.swing.JButton btnusers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lbltime;
    private javax.swing.JPanel pnl5;
    private javax.swing.JTable tblspeciatypeDetailsl;
    private javax.swing.JTextField txtspecialDescription;
    private javax.swing.JTextField txtspecialDoctId;
    private javax.swing.JTextField txtspecialDoctname;
    // End of variables declaration//GEN-END:variables

    private void clearAll() {
        txtspecialDoctId.setText("");
        txtspecialDoctname.setText("");
        txtspecialDescription.setText("");
    }

    private void getAllSpecialtype() {
        
        try {
            dtm.setRowCount(0);
            ArrayList<DoctorDTO> allSpecialType=DoctorController.getAllDoctor();
            for(DoctorDTO doc:allSpecialType){
                Object[] rowData={doc.getDoctId(),doc.getDoctName(),doc.getDoctSpecialType()};
                dtm.addRow(rowData);
            }
            
            } catch (ClassNotFoundException ex) {
            Logger.getLogger(SpecialType.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(SpecialType.class.getName()).log(Level.SEVERE, null, ex);
        }
       
            
//        try {
//            dtm.setNumRows(0);
//            ArrayList<SpecialtypeDTO> allSpecialtype=SpecialtypeController.getAllSpecialtype();
//            for(SpecialtypeDTO sp : allSpecialtype) {
//                Object[] rowData={sp.getDoctId(),sp.getDoctName(),sp.getDescription()};
//                dtm.addRow(rowData);
//            }
//            
//        } catch (ClassNotFoundException ex) {
//            Logger.getLogger(SpecialType.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (SQLException ex) {
//            Logger.getLogger(SpecialType.class.getName()).log(Level.SEVERE, null, ex);
//        }
        
    }

    private void autoSettime() {
       new Thread (new Runnable() {
            @Override
            public void run() {
                while(true){   
                    Date curDate = new Date();
                    SimpleDateFormat dateFormat =new SimpleDateFormat("HH:mm:ss:aa");
                    String currentTime =dateFormat.format(curDate);
                    lbltime.setText(currentTime);
                    try{
                        Thread.sleep(1000);
                    }catch(InterruptedException ex){
                        
                    }
                    
                }
            }
        }).start();
    }

    private void settDate() {
       lbldate.setText(LocalDate.now().toString()); 
    }
    
}
